[project]
name = "computethinking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo[recommended]>=0.14.11",
    "mkdocs-glightbox>=0.4.0",
    "mkdocs-material>=9.6.15",
]
